const USER_SELECT = [
      "id",
      "supabase_user_id",
      "email",
      "full_name",
      "company_name",
      "avatar_url",
      "credit_balance",
      "is_pro",
      "subscription_type",
      "auth_provider",
      "owner",
      "device_id",
      "received_initial_credit",
      "initial_credit_date",
      "created_at",
      "updated_at",
      "web_session_version",
      "mobile_session_version",
      "last_web_login",
      "last_mobile_login",
      "is_in_trial",
      "has_used_trial",
      "trial_started_at",
      "active_team_id",
      "team_max_members",
      "team_subscription_active",
      "platform",
      "app_version",
      "theme_mode",
      "metadata_updated_at",
      "preferred_language",
      "country",
      "country_updated_at",
    ].join(", ");
module.exports = { USER_SELECT };
