const clean = value => typeof value === 'string' ? value.trim() : '';

function isFashionCampaignShoot(settings = {}, modes = {}) {
  return !['shoes', 'jewelry'].includes(clean(settings?.productCategory).toLowerCase()) &&
    !['isColorChange', 'isPoseChange', 'isEditMode', 'isRefinerMode', 'isBackSideAnalysis']
      .some(key => modes[key] === true);
}

function isCleanWhiteStudio(settings = {}) {
  // Read the selected location, never a white garment or the model's skin.
  const location = clean(settings?.location);
  return /\bwhite\b|beyaz/i.test(location) &&
    /studio|stüdyo|st[uü]dyo|backdrop|background|cyclorama|\bfon\b/i.test(location);
}

function buildFashionFocusDirective(settings = {}) {
  const focus = clean(settings?.focusArea).toLowerCase();
  const framing = clean(settings?.framing).toLowerCase();
  // A chosen camera crop takes priority over a broad product-focus category.
  if (framing && framing !== 'auto') return `PRODUCT FOCUS: Emphasize ${focus || 'the product'} within the explicitly selected ${framing} camera crop. Do not change that crop to satisfy a focus category.`;
  if (focus === 'upper_body') return `UPPER-BODY FASHION COMPOSITION: Frame the head, torso and complete upper garment to the hips, with natural headroom and visible environment beside both arms. Prioritize the blouse/top without forcing an edge-to-edge portrait or pushing the person into the extreme foreground. Place the model inside the scene at a believable depth; an upper-body crop does not mean the model must fill the frame width. Do not cut off the garment hem merely to crop at the waist.`;
  if (focus === 'lower_body') return `LOWER-BODY FASHION COMPOSITION: Emphasize the waist, lower garment and feet, leaving enough surrounding ground and side space to establish their real scale and contact with the setting. Do not force an edge-to-edge cutout of the lower body.`;
  return '';
}

function buildSceneIntegrationDirection({settings = {}} = {}) {
  const tight = ['close_up', 'detail'].includes(clean(settings?.focusArea)) || ['close_up', 'chest_up'].includes(clean(settings?.framing));
  return `ON-LOCATION PHOTOGRAPHIC INTEGRATION:
Compose one camera exposure of a person physically present in a three-dimensional place. Reconstruct and relight the selected identity from its recognizable facial geometry; discard the reference portrait's front fill, catchlights, skin highlights, exposure, cutout outline and frozen expression. Identity fidelity never requires copying the portrait's lighting or beauty retouching.
Before describing the person, establish the scene's dominant light direction, hardness and shadow direction, then place the person at a specific depth relative to nearby architecture or natural landmarks. Skin, hair, garment and surfaces at that same position share the same key light, shadow softness, exposure and local reflected light. In direct sun, corresponding facial planes and folds receive directional sun and real self-shadow; in open shade, both the person and the immediately surrounding surfaces receive the same sky fill. Never light the face as an independent beauty-studio portrait while the surroundings remain in hard sunlight. Preserve true garment colors while allowing physically plausible shaded and illuminated tones.
Use one horizon, camera height and perspective for human anatomy and architecture; nearby columns, doors and furniture provide believable scale, not a miniature background behind an oversized foreground person. ${tight ? 'Honor the explicitly selected close-up/detail crop; establish integration through coherent light, edge detail and visible local context without forcing a wide view.' : 'Leave environmental breathing room alongside the model and establish near, subject-plane and farther scene layers. Choose camera distance and a moderate focal length appropriate to the selected crop; do not default to a long-lens isolated beauty portrait. Keep nearby surfaces at the subject depth similarly resolved; let distant detail soften progressively with distance, not an artificial blurred-background mask.'}
Anchor visible feet, hands and body contacts with accurate contact shadows and occlusion where they actually meet a surface; when cropped, do not add feet or widen the requested crop merely to show a ground shadow. Hair edges, skin and fabric share natural photographic sharpness, texture and highlight roll-off with the scene; no bright cutout halo, waxy skin, plastic specular sheen or uniformly hyper-sharp subject against smeared scenery.
A saved location description is a venue inventory, not a separate finished landscape to paste a person over. Its stock words such as wide shot, empty or vacant describe the source venue, not a command to exclude the model or override the user's camera crop. Retain the architecture and choose the camera viewpoint for this fashion photograph. Atmospheric adjectives in a saved venue description do not prescribe the model's mood or performance; a serene place does not require a serene expression. Explicit user-written lighting, viewpoint and composition instructions take priority.`;
}

function buildFashionPoseContext({settings = {}, hasUserPose = false} = {}) {
  if (!hasUserPose) return '';
  return `POSE INSPIRATION: ${settings.pose || "Use the supplied pose image as a general direction"}. The selected pose and any pose image are a starting point, not an exact body-position or facial-expression template. A nearby, better art-directed fashion stance and expression are welcome when a literal copy looks stiff or casual. Preserve the overall intent and product visibility; honor any explicit pose or expression requirement written in Additional details and any separately selected mood.`;
}

function buildFashionBodyLanguageDirection() {
  return `FASHION BODY LANGUAGE: Design the model's body language for THIS garment, setting, composition and selected mood, as a fashion photographer would direct a real person on location. The result should communicate confident, natural fashion presence through the relationship of posture, gesture, gaze and expression, rather than a person stiffly waiting to be photographed. Derive the energy and stance from the clothing's silhouette, drape and character and the scene's atmosphere; make your own concrete posing decisions instead of reusing a default or copying the identity portrait. No prescribed hand position, mandatory limb angle or fixed sequence applies across shoots. Avoid passive mannequin stiffness and forced theatricality. Choose a characterful, expressive photographic moment with an identifiable attitude and a reason for the gesture and expression beyond merely displaying the outfit. Describe the visible behavior that carries that attitude. Passive standing with a neutral gaze is not a substitute for that decision unless the user requested a neutral catalog treatment. Treat garment fidelity as a design constraint, not an instruction to photograph a neutral fitting-room stance. Keep the product's important details readable without freezing the body to expose them. Adapt naturally to age, abilities, coverage and the visible crop; explicit user-written pose requirements and separately selected mood take priority. Preserve the scene-matched lighting, believable anatomy and garment fidelity throughout.`;
}

function buildFashionCampaignDirection({settings = {}, hasStyleReference = false} = {}) {
  if (hasStyleReference) return ''; // Explicit street/editorial references own their art direction.
  return `FINISHED FASHION CAMPAIGN:
Preserve the product's exact construction, relaxed or fitted cut, length, colors, piping, seams and branding; a tiny embroidered symbol is the actual reference shape, never a newly invented monogram. Photograph the recognizable person anew: the model reference controls identity and apparent age, not its original clothing, frontal portrait stance, expression, camera relationship or flat lighting. Reconstruct their performance and the whole photograph together rather than changing only the background of the reference portrait. Preserve any explicitly selected hairstyle and modesty requirements.
Use deliberate, anatomically natural fashion direction: clear body lines, believable weight distribution, a considered relationship between shoulders and hips, and hands placed to keep the product readable. Treat selected pose presets and pose images as flexible inspiration: adjust stance, arm placement, head angle and expression to a nearby fashion pose when literal copying would look stiff or casual. Preserve separately selected mood, explicit written pose requirements and framing. A generic confident smile is a small, self-assured closed-lip smile; an explicitly requested broad smile or laugh must remain broad. Do not automatically turn every model into a broadly grinning frontal portrait. Choose appropriate direction for the person's age and abilities; babies are safely supported, never posed as standing adult models. Product fit stays faithful rather than being tightened to create the pose.
${buildFashionBodyLanguageDirection()}
Light shapes the face and garment with intentional dimensional shading and enough fill to preserve material detail. Preserve neutral product colors and natural skin texture. Fashion character comes from pose, styling, light and composition, not an automatic warm grade or beauty filter. Explicit user details override these defaults.
${buildSceneIntegrationDirection({settings})}
${isCleanWhiteStudio(settings) ? `CLEAN WHITE BACKDROP: The complete visible background is an edge-to-edge seamless neutral-white field, not a behind-the-scenes photograph of a studio room. Keep softboxes, stands, reflectors, cables, cameras, windows, ceiling fixtures, room corners and backdrop edges outside the frame and reflections. Describe the effect of illumination, not visible lighting equipment. Sunny/afternoon settings affect the light quality only; they do not require a visible window. A generic white-studio location reference establishes the backdrop, not equipment or room boundaries to reproduce. Explicit user requests to show a real location's architecture or behind-the-scenes equipment take precedence.` : ''}`.trim();
}

function buildFashionCampaignEnhanceInstruction({settings = {}, originalPrompt = '', customDetail = '', context = '', multipleAnglesCount = 0, kombinItemCount = 0, isMultipleProducts = false} = {}) {
  return `Write the final English image-editing prompt for a finished, deliberately art-directed fashion campaign. Start with "Create a new fashion campaign photograph" and return four or five connected paragraphs, no commentary. This is a newly photographed performance by the same person wearing the same product, not background replacement behind an existing portrait. Do not open with a command to replace only the background or preserve the reference photograph as a composition. Analyze the supplied product visually and derive a distinctive campaign direction from its actual cut, fabric and intended use. Do not merely add the words "editorial" or "high-end" to a casual portrait.

First decide the visual idea of this campaign from the garment's character and the selected setting. Open with the person actively embodying that idea in a specific photographic moment; describe visible behavior, attitude and expression that make this photograph feel authored. Do not spend the opening on a vacant landscape or an inventory of facial features. Give the opening paragraph meaningful space for the chosen performance: a specific visible behavior and its relationship to camera, garment and environment, invented for this shoot. Do not resolve the brief as merely standing, looking calm or reflective, and showing the blouse. The photographed moment should carry character and editorial intention even without the label fashion. Use the selected mood if present; otherwise choose the attitude from the garment, not from stock serene/peaceful words in the location description. Do not narrate a concept without translating it into visible behavior. Develop the overall relationship between the person's performance, the camera and the setting instead of adding stronger fashion adjectives. Then establish the person's scene depth and the physically shared light on them and a nearby landmark, retaining one coherent exposure and realistic focus transition. Design the body language from this garment and setting, then describe your chosen direction concretely enough for the image model to render. Do not return only abstract labels such as poised or editorial, but do not follow a predetermined pose formula either. Judge the posture, gesture, gaze and expression together: would this read as a deliberately directed fashion photograph or a stiff person waiting for a snapshot? If it is the latter, revise the direction while keeping the product readable and the anatomy natural. When a pose guide is selected, use its overall intent as flexible inspiration and allow a nearby fashion interpretation. Explicit requirements written in Additional details and separately selected mood take priority. The model portrait provides identity, not its stance, expression or lighting. Respect age, body measurements, coverage, abilities and framing. Do not impose a signature stance, fixed hand position or mandatory body-angle arrangement on every garment.

Then describe the exact observed garment and its physical fit. Inspect small emblems and trims in the product views; preserve their observed shape, scale and placement without guessing a brand, spelling or new design. Describe only visible construction, not invented premium fabrics or extra hardware. Keep the source fit and hem length, natural drape and realistic contact with the body; do not automatically tuck in or cinch casual tops. Styling supports the product without covering important details.

Describe the selected setting and a precise lighting treatment. In a clean white-backdrop shoot, frame a continuous white field rather than a studio room. Shape facial planes and fabric with off-camera directional light and restrained fill; all lighting devices stay outside the photograph. Describe illumination visually without asking the generator to place a softbox or window in frame. Use a lens, depth of field and camera height suitable for the user's framing, keeping important garment details resolved. Elsewhere preserve the selected environment and its architecture; do not replace outdoor scenes with a white studio. Keep true product colors and skin texture. Avoid automatic presets, warmth, grain or flat front lighting.

${buildFashionCampaignDirection({settings})}
${multipleAnglesCount > 1 ? `The product grid contains ${multipleAnglesCount} views of ONE product. Reconcile them as construction evidence, not separate garments or a collage. Use close-ups to ground tiny details.` : ''}
${isMultipleProducts || kombinItemCount > 1 ? 'OUTFIT: Identify every distinct supplied product and dress the model in all of them as one coherent outfit. Preserve each item separately and its intended layering. The grid cell order is not clothing order. Do not omit items in favor of the hero garment.' : ''}

USER BRIEF (explicit written details take precedence; the generated Pose field is flexible inspiration, not an exact-copy requirement):
${originalPrompt}
${customDetail ? `Additional details: ${customDetail}` : ''}

SELECTED SETTINGS AND REFERENCE ROLES (translate internal keys to natural English; preserve the actual choices):
${context}

Finish by checking product fidelity, the overall pose inspiration, explicit written gesture/expression requests, appropriate coverage, framing, and background. For a white seamless request, describing a light source never authorizes showing the equipment. Output the photographic prompt only.`;
}

module.exports = {isFashionCampaignShoot, isCleanWhiteStudio, buildFashionFocusDirective, buildSceneIntegrationDirection, buildFashionBodyLanguageDirection, buildFashionPoseContext, buildFashionCampaignDirection, buildFashionCampaignEnhanceInstruction};
