app = "diress"
primary_region = "fra"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["paketo-buildpacks/nodejs"]

[env]
  NODE_ENV = "production"
  PORT = "3001"   # Fly UI’de verdiğin PORT ile eşleşsin

[[services]]
  internal_port = 3001
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.http_checks]]
    method = "GET"
    path = "/api/status"
    interval = "15s"
    timeout = "2s"
    grace_period = "30s"
