app = "diress"
primary_region = "fra"

[env]
  NODE_ENV = "production"
  PORT = "3000"   # app process.env.PORT kullanacak

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls","http"]
